config/routes.rb
Rails.application.routes.draw do
  root "sessions#welcome"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/signup", to: "users#new"
  get '/auth/:google_oauth2/callback' => 'sessions#google'

  get '/order', to: 'recipes#order'
  get '/recipes/search', to:'recipes#search'
  post '/search', to:'recipes#results'
  

  # resources :ingredients
  
  resources :recipes do
    resources :comments
  end

  resources :users, only: [:show, :new, :create, :edit, :update]
  resources :recipes
  # resources :recipes
  resources :comments, only: [:show, :index, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  validates_presence_of :title, :body, :rating
   validate :rating_range

  private

  def rating_range
    if (0..5).none? { |num| num == rating }
      errors.add(:rating, "must be between 0-5")
    end
  end 

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    load_and_authorize_resource


    def index
        if params[:recipe_id]
          @recipe = Recipe.find_by_id(params[:recipe_id])
          # also verify that recipe exists
          @comments = @recipe.comments
        else 
          @comments = Comment.all
        end
      end
    
    def show
        if params[:recipe_id]
          @recipe = Recipe.find_by_id(params[:recipe_id])
          
          set_comment
            if @recipe.comments.include?(@comment)
                render :show
            else
                flash.now[:notice] = "Comment doesn't belong to recipe."
                redirect_to recipes_path
            end
        else 
          set_comment
        end
    end
    
    def new
        if params[:recipe_id]
          @recipe = Recipe.find_by_id(params[:recipe_id])
          @comment = @recipe.comments.build
        else 
          @comment = Comment.new
        end
    end
    
    def create
        if params[:recipe_id]
          @recipe = Recipe.find_by_id(params[:recipe_id])
          @comment = @recipe.comments.build(comment_params)
          @comment.user_id = current_user.id
        else 
          @comment = Comment.new(comment_params)
        end
    
        if @comment.save
          redirect_to @recipe
        else
            flash.now[:notice] = @comment.errors.full_messages.to_sentence
            render :new
        end
    end

    def edit
        if params[:recipe_id]
            @recipe = Recipe.find_by_id(params[:recipe_id])
            @comment = @recipe.comments.find_by(id: params[:id])
        else 
            set_comment
        end
    end 
  
    def update
        if params[:recipe_id]
            @recipe = Recipe.find_by_id(params[:recipe_id])
            @comment = @recipe.comments.find_by(id: params[:id])
            @comment.update(comment_params)
        else 
            set_comment
            @comment.update(comment_params)
        end
      
        if @comment.valid?
            @comment.save
            if params[:recipe_id] 
             redirect_to recipe_comment_path(@recipe, @comment)
            else
            redirect_to comment_path( @comment)
            end
        else
            flash.now[:notice] = @comment.errors.full_messages.to_sentence
            render :edit
        end
    end 
    
    def destroy
        set_comment
        @comment.destroy
        # redirect_to root_path
        redirect_to recipes_path
    end 
    
    private
    
    def comment_params
        params.require(:comment).permit(:id, :title, :rating, :body)
    end
    
    def set_comment
        @comment = Comment.find_by_id(params[:id])
    end
end

app/helpers/comments_helper.rb
module CommentsHelper

    def recipe_name(comment)
        comment.recipe.name
    end 

end

app/views/comments/_form.html.erb
<%= form_with model:[@recipe, @comment], local: :true do |f| %>
<%= f.label :rating %>
<%= f.number_field :rating %><br>
<%= f.label :title %>
<%= f.text_field :title %><br>
<%= f.label :body %>
<%= f.text_area :body %><br>
<%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= render :partial => 'form' %>

app/views/comments/index.html.erb
<% if @recipe %>
<h4> <%= @recipe.name %>'s  Reviews:</h4>
<ul>
 <% @comments.each do |comment| %>
 <li><%= link_to comment.title, recipe_comment_path(@recipe, comment) %></li> 
 <% end %>
</ul>
<% else %>
<h4>All Reviews:</h4>
<ul>
 <% @comments.each do |com| %>
 <li><%= link_to com.title, com %></li> 
 <% end %>
</ul>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>
<%= render 'form' %>

app/views/comments/show.html.erb
<h1><%= @comment.title %></h1>
<h2>By:  <%= link_to full_name(@comment.user), user_path(@comment.user) %></h2>
<h3><%= @comment.rating %> Stars</h3>
<p><%= @comment.body %></p>
<p>- <%= formatted_time(@comment) %></p>
<h4>Reviewed Recipe: <%= link_to recipe_name(@comment), recipe_path(@comment.recipe) %></h4>

<% if current_user == @comment.user %>
<% if params[:recipe_id] %>
<h6><%= button_to "Edit Comment", edit_recipe_comment_path(@recipe, @comment), method: :get %></h6>
<% else %>
<h6><%= button_to "Edit Comment", edit_comment_path(@comment), method: :get %></h6>
<% end %>
<h6><%= button_to "Delete Comment", @comment, method: :delete, data: {confirm: "Delete this comment?"} %></h6>
<% end %>