config/routes.rb
Rails.application.routes.draw do
  root "sessions#welcome"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/signup", to: "users#new"
  get '/auth/:google_oauth2/callback' => 'sessions#google'

  get '/order', to: 'recipes#order'
  get '/recipes/search', to:'recipes#search'
  post '/search', to:'recipes#results'
  

  # resources :ingredients
  
  resources :recipes do
    resources :comments
  end

  resources :users, only: [:show, :new, :create, :edit, :update]
  resources :recipes
  # resources :recipes
  resources :comments, only: [:show, :index, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  
  has_many :comments, :dependent => :delete_all
  has_many :ingredients, :dependent => :delete_all
  has_many :dietary_restrictions, :dependent => :delete_all
  has_many :users, through: :comments

  validates_presence_of :name, :steps, :description

  accepts_nested_attributes_for :ingredients, reject_if: proc {|ing| ing['name'].blank? || ing['count'].blank? || ing['measurement'].blank? }
  accepts_nested_attributes_for :dietary_restrictions, reject_if: proc {|diet| diet['name'].blank? }

  scope :search, -> (query) { where("LOWER(name) LIKE ?", "%#{query.downcase}%") }
  
  
  def overall_rating
    ratings = self.comments.map {|c| c.rating}
    rating_sum = ratings.reduce(:+)
    mean_rating = (rating_sum/self.comments.count) unless self.comments.count == 0
    self.comments.count == 0 ? "No Reviews Yet" : "#{mean_rating} Stars"
  end 

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    load_and_authorize_resource
    before_action :set_recipe, only: [:show, :edit, :update, :destroy]

    def new
        @recipe = Recipe.new
        10.times { @recipe.ingredients.build }
        5.times { @recipe.dietary_restrictions.build }
    end 

    def create
        @recipe = current_user.recipes.new(recipe_params)
        if @recipe.valid?
            @recipe.save
            # redirect_to recipe_path
            redirect_to recipe_path(@recipe)
        else
            flash.now[:notice] = @recipe.errors.full_messages.to_sentence
            render :new
        end
    end 

    def show
        if @recipe
            render :show
        else
            flash.now[:notice] = "Recipe not Found!"
            redirect_to recipes_path
        end
    end 

    def index
        @recipes = Recipe.all
    end 

    def edit
    end 

    def update
        @recipe.update(recipe_params)
        if @recipe.valid?
            @recipe.save
            redirect_to recipe_path(@recipe)
        else 
            flash.now[:notice] = @recipe.errors.full_messages.to_sentence
            redirect_to edit_recipe_path(@recipe)
        end 
    end 

    def destroy
        @recipe.destroy
        # redirect_to root_path
        redirect_to recipes_path
    end 

    def order
        @recipes = Recipe.order(name: :asc)
    end 

    def search
    end
  
    def results
      @recipes = Recipe.search(params[:q])
      render :index
    end

    private

    def recipe_params
        params.require(:recipe).permit(
            :id,
            :name,
            :description,
            :steps,
            :stars,
            :dietary_restrictions,
            ingredients_attributes:[:id, :name, :count, :measurement] ,
            dietary_restrictions_attributes:[:id, :name]
        )
    end

    def set_recipe
        @recipe = Recipe.find_by(id: params[:id])
    end

end

app/helpers/recipes_helper.rb
module RecipesHelper

    def formatted_time(obj)
        obj.created_at.strftime("%d %b %Y")
    end 

end

app/views/recipes/_form.html.erb
<%= form_with model:@recipe, local: :true do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <%= f.label :description %>
    <%= f.text_field :description %><br>
    <h4>Dietary Restrictions: </h4>
    <%= f.fields_for :dietary_restrictions do |diet| %>
        <%= diet.label :name %>
        <%= diet.text_field :name %><br>
    <% end %>
    <br>
    <h4>Ingredients: </h4>
    <%= f.fields_for :ingredients do |ing| %>
        <%= ing.label :count %>
        <%= ing.number_field :count, step: :any %>
        <%= ing.label :measurement %>
        <%= ing.text_field :measurement %>
        <%= ing.label :name %>
        <%= ing.text_field :name %><br>
    <% end %>
    <%= f.label :steps %>
    <%= f.text_area :steps, size: "70x15" %><br>
    <%= f.submit %>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit <%= @recipe.name %></h1>
<%= render :partial => 'form' %>

app/views/recipes/index.html.erb
<h1>All Recipes</h1>

<h2><%= link_to "Search For Recipes", recipes_search_path %></h2>
<h2><%= link_to "Order by Recipe Name", order_path %></h2>

<% @recipes.each do |recipe| %>
<%= link_to recipe.name, recipe_path(recipe) %><br>
<% end %>

app/views/recipes/new.html.erb
<h4>Create New Recipe!</h4>
<%= render 'form' %>

app/views/recipes/order.html.erb
<h1>All Recipes by Name</h1>

<% @recipes.each do |recipe| %>
<%= link_to recipe.name, recipe_path(recipe) %><br>
<% end %>

app/views/recipes/search.html.erb
<%= form_with url:"/search", local: :true  do |form| %>
  <%= form.label "Search for:"%>
  <%= form.text_field :q%>
  <%= form.submit "Search"%>
<% end %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>
<h2><%= @recipe.overall_rating %> </h2>
<h4>By: <%= link_to full_name(@recipe.user), user_path(@recipe.user) %></h4>
<p>Created: <%= formatted_time(@recipe) %></p>
<p>Description: <%= @recipe.description %></p>
<h4>Dietary Restrictions: </h4>
<ul>
<% @recipe.dietary_restrictions.each do |diet| %>
<li> <%= diet.name %> </li>
<% end %>
</ul>
<h4>Ingredients:</h4>
<ul>
<% @recipe.ingredients.each do |ing| %>
<li> <%= ing.count %> <%= ing.measurement %> <%= ing.name %> </li>
<% end %>
</ul>

<h4>Instructions: </h4>
<p><%= @recipe.steps %></p>

<h4>Comments: </h4>

<% @recipe.comments.each do |comment| %>
<p> <strong><%= comment.title %></strong> - <%= link_to full_name(comment.user), user_path(comment.user) %><br>
<%= comment.rating %> Stars<br>
<%= comment.body %> <p><br>
<% end %>


<%= link_to "Add a Comment", new_recipe_comment_path(@recipe) %><br>
<%= link_to "See all Comments", recipe_comments_path(@recipe) %>
<% if current_user == @recipe.user %>
<h6><%= button_to "Edit Recipe", edit_recipe_path(@recipe), method: :get %></h6>
<h6><%= button_to "Delete", @recipe, method: :delete, data: {confirm: "Delete this recipe?"} %></h6>
<% end %>