config/routes.rb
Rails.application.routes.draw do
  root "sessions#welcome"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/signup", to: "users#new"
  get '/auth/:google_oauth2/callback' => 'sessions#google'

  get '/order', to: 'recipes#order'
  get '/recipes/search', to:'recipes#search'
  post '/search', to:'recipes#results'
  

  # resources :ingredients
  
  resources :recipes do
    resources :comments
  end

  resources :users, only: [:show, :new, :create, :edit, :update]
  resources :recipes
  # resources :recipes
  resources :comments, only: [:show, :index, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :comments
    has_many :commented_recipes, through: :comments, source: :recipe
    has_many :recipes
    has_secure_password

    validates_presence_of :email, :first_name, :last_name
    validates_uniqueness_of :email 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :verified_user, only: [:new, :create]
    before_action :set_user, only: [:show, :edit, :update, :destroy]


    def new
        @user = User.new
    end 

    def create
        @user = User.new(user_params)
        if @user.valid?
            @user.save
            session[:user_id] = @user.id
            # redirect_to user_path
            redirect_to user_path(@user)
        else
            flash.now[:notice] = @user.errors.full_messages.to_sentence
            render :new
        end
    end 

    def show
        @user = User.find_by(id: params[:id])
    end

    def edit
    end 

    def update
        @user.update(user_params)
        if @user.valid?
            @user.save
            redirect_to user_path(@user)
        else 
            flash.now[:notice] = @user.errors.full_messages.to_sentence
            redirect_to edit_user_path(@user)
        end 
    end 

    def destroy
        @user.destroy
        redirect_to welcome_path
    end 

    private

    def set_user
        @user = User.find_by(id: params[:id])
    end 

    def user_params
        params.require(:user).permit(
            :first_name, 
            :last_name,
            :email,
            :password
        )
    end 

end

app/helpers/users_helper.rb
module UsersHelper
    
    def full_name(user) 
        "#{user.first_name} #{user.last_name}"
    end 

end

app/views/users/_form.html.erb
<%= form_with model:@user, local: :true do |f|%>
  <%= f.label :email %><br>
  <%= f.text_field :email %><br>
  <%= f.label :first_name %><br>
  <%= f.text_field :first_name %><br>
  <%= f.label :last_name %><br>
  <%= f.text_field :last_name %><br>
  <%= f.label :password %><br>
  <%= f.password_field :password %><br>
  <%= f.submit %>
<%end%>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= render :partial => 'form' %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= full_name(@user) %>'s Profile</h1>
<%=link_to "Edit User", edit_user_path(@user)%>
<h2>Recipes: </h2>
<ul>
<% @user.recipes.each do |recipe| %>
<li><%= link_to recipe.name, recipe_path(recipe) %><br>
    <%= recipe.description %>
</li><br>
<% end %>
</ul>

<h2>Reviews: </h2>
<ul>
<% @user.comments.each do |comment| %>
<li><%= link_to comment.title, comment_path(comment) %><br>
    <strong><%= comment.rating %> Stars</strong><br><br>
    <%= comment.body %><br><br>
    Reviewed Recipe: <%= link_to recipe_name(comment), recipe_path(comment.recipe) %>
</li><br>
<% end %>
</ul>