config/routes.rb
Rails.application.routes.draw do
  root "sessions#welcome"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/signup", to: "users#new"
  get '/auth/:google_oauth2/callback' => 'sessions#google'

  get '/order', to: 'recipes#order'
  get '/recipes/search', to:'recipes#search'
  post '/search', to:'recipes#results'
  

  # resources :ingredients
  
  resources :recipes do
    resources :comments
  end

  resources :users, only: [:show, :new, :create, :edit, :update]
  resources :recipes
  # resources :recipes
  resources :comments, only: [:show, :index, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="menu">
        <% if logged_in? %>
        <div class="navbar">
          <%= link_to "Logout", logout_path, method: "delete" %>
          <%= link_to "Search All Recipes", recipes_path%>
          <%= link_to "Create A New Recipe", new_recipe_path%>
          <%= link_to "User Profile", user_path(current_user) %>
          </div>
        <% else %>
        <div class="navbar">
          <%= link_to "Login", login_path %> 
          <%= link_to "Signup", signup_path %>
          </div>
          <% end %>
      </nav>
    <% if flash[:notice] %>
      <div class="alert"><%= flash[:notice] %><br></div>
    <% end %>
    <%= yield %>
  </body>
</html>